# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af85be435a72f866787f9063cf1a9bac250c996385ef65e3c0b6543fde2003bc7283e296b2fc35d250178fe90d650f16e1b447cbf39557f718484d0350547a0

test:
  secret_key_base: 8639888ecdc69d3e578fe9aacb68e48f90b160a5ac2570a372647ec80263b0c71722e137041d2f37b4d6ff65dc7fc1fd2982876b4f7a9df91d67c9fc4deeeee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
